### PR TITLE
New files added for chrome extension

### PR DESCRIPTION
**Pull request by amogh-nagar**
Added new files for Extingo(Chrome extension)

### CODE REVIEW

**Comment by hkaur008** [comment]
Please make a separate folder with the name of the extension in the repository  
Put your all source code in that folder, 
Put a screenshot of your extension  in readme.MD file 👍🏻 
Make a pull request.

**Review by hkaur008 — APPROVED** [review]

**Review by hkaur008 — CHANGES_REQUESTED** [review]
- [x] Put your source code in a separate folder , name it with name of your extension
- [x] Put a screenshot of your extension in the readme.MD
Make a pull request 👍🏻

**Comment by amogh-nagar** [comment]
Updated file arrangement and added screenshot in Readme.md

**Review by hkaur008 — APPROVED** [review]

**Comment by hkaur008** [comment]
> Updated file arrangement and added screenshot in Readme.md

Linkedin  missing !

**Pull request merged**
